update to later codebase

diff --git a/usrlocalbin/dr_compress b/usrlocalbin/dr_compress
--- a/usrlocalbin/dr_compress
+++ b/usrlocalbin/dr_compress
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -o nounset
 
-# die MESSAGE 
+# die MESSAGE
 function die {
    if [ -n "$1" ]; then
-      echo "$1" <&2
+      echo "$1" >&2
    else
-      echo "Unexpected error. Exiting."<&2
+      echo "Unexpected error. Exiting.">&2
    fi
    exit 1
 }
@@ -23,12 +23,11 @@ if [ -e "$ARCHIVEPATH" ]; then die "Archive $1 already exists. Aborting." ; fi
 if [ ! -d "$SOURCEFOLDER" ]; then die "dr_compress: Source folder does not exist: $SOURCEFOLDER"; fi
 
 # default to empty string if doesn't exist, then test for empty string.
-if [ -n "${PASS-}" ]; then 
-   PASSCMD="-p${PASS}"; 
+if [ -n "${PASS-}" ]; then
+   tar cz -C "$SOURCEFOLDER" . | openssl enc -aes-256-cbc -e -k "${PASS}" > "$ARCHIVEPATH"
+   [ $? -eq 0 ] || die "Failed to create encrypted archive."
 else
-   PASSCMD=""
    echo "WARNING: No password supplied. Backup is not encrypted!">&2
+   tar czf "$ARCHIVEPATH" -C "$SOURCEFOLDER" .
+   [ $? -eq 0 ] || die "Failed to create archive."
 fi
-
-tar cf - -C "$SOURCEFOLDER" . | 7za a -si "${PASSCMD}" "$ARCHIVEPATH"  >/dev/null 2>&1
-if [ $? -ne 0 ]; then die "Failed to create archive." ; fi
